hex/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from max import views

from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls), # url to load the site
    url(r'^$', views.index, name='index'),  # url to load index function
    url(r'^max/', include('max.urls')), # url to include urls present in max\urls.py
    url(r'^database/', views.test, name='database'),  # url to load test function
    url(r'^special/', views.special, name='special'),  # url to load special function
    url(r'^logout/$', views.user_logout, name='logout'),  # url to call logout page
    path('ajax/load-electronics/', views.load_electronics, name='ajax_load_electronics'),  # url for ajax call to call load_electronics function
    path('ajax/load-seller/', views.load_seller, name='ajax_load_seller'),  # url for ajax call to call load_seller function
    path('ajax/load_list/', views.load_list, name='ajax_load_list'),  # url for ajax call to call load_list function
    path('ajax/subscribe/', views.subscribe, name='ajax_subscribe'),   # url for ajax call to call subscribe function
]

max/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from django.conf.urls import url

app_name = 'max'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),  # url to load register function
    url(r'^user_login/$', views.user_login, name='user_login'),  # url to call login page
    path(r'^/Electronics/(?P<id>)/$', views.Electronics, name="populate"),  # url to call Electronics module
    path(r'^/Seller/(?P<id>)/$', views.Seller, name="populate"),  # url to call Seller module
    path(r'^ajax/load-electronics/', views.load_electronics, name='ajax_load_electronics'),  # url for ajax call to call load_electronics function
    path(r'^ajax/load-seller/', views.load_seller, name='ajax_load_seller'),  # url for ajax call to call load_seller function
    path(r'^ajax/load_list/', views.load_list, name='ajax_load_list'), # url for ajax call to call load_list function
    path(r'^ajax/subscribe/', views.subscribe, name='ajax_subscribe'), # url for ajax call to call subscribe function
]

templates/Select_Electronics.html
<!--Html page to select the electronic items and seller -->

{% extends 'base.html' %}
{% block body_block %}
{% load render_table from django_tables2 %}

{% load static %}
<!--<!doctype html>-->
<html>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<head>
    <p><b> SELECT THE ITEM YOU WANT TO BUY</b></p>
</head>
<body id="body">
<div class="col-xs-6" id="category_div" data-electronics-url="{% url 'ajax_load_electronics' %}">
    <select class="form-control" name="select1" id="category" onchange="load_electronics()">
        {%for r in nam %}
        <option value={{r.id}}>{{r.item_name}}</option>
        {%endfor%}
    </select>
</div>

<div class="col-xs-6">
    <select class="form-control" name="select2" id="electronics" data-sellers-url="{% url 'ajax_load_seller' %}" onchange="load_seller()">
        {% for r in nex %}
        <option value>--------</option>
        <option value={{r.id}}>{{r.specification }}</option>

        {%endfor%}
    </select>
</div>

<div class="table" id="sellercategory_div">

<table style="width:100%" name="select3" id="sellercategory" >

<br></br>
    <br></br>

    <tr>
        <th>SR NO</th>
        <th>SPECIFICATIONS</th>
        <th>NAME</th>
        <th>ADDRESS</th>
        <th>EMAIL ID</th>
        <th>PRICE</th>
        <th>SELECT</th>
    </tr>

    {% for z in sell %}
    <tr>
        <td>{{ z.srno }}</td>
        <td>{{z.model_seller}}</td>
        <td>{{z.name}}</td>
        <td>{{z.address }}</td>
        <td>{{z.email_id }}</td>
        <td>{{z.price }}</td>
        <th><button id="{{z.srno}}" name="t" onclick="collectdata(this);">BUY</button></th>
    </tr>
    {%endfor%}
</table>
</div>


</body>


{% block javascript %}


<script>
// Defining a function to call when
function load_seller() {      //defining of function

//instance of category select html element
var $select3 = document.getElementById("electronics");
var url = $("#electronics").attr("data-sellers-url");
console.log($("#select3").value);
console.log(url);
$.ajax({                       // initialize an AJAX request
        url: url,                    // set the url request
        data: {
          'model_seller_id': $select3.value       // add the seller id to the GET parameters
        },
        success: function (data) {   // 'data' is the return of the 'load_seller' view function
          $("#sellercategory").html(data);  // replace the contents of the seller input with the data that came from the server
        },
        failure: function(errMsg) {
            alert(errMsg);       //message displayed when error occured
        }
      });
}


// Defining a function to call when
function load_electronics() {

//instance of category select html element
var $select1 = document.getElementById("category");
var url = $("#category_div").attr("data-electronics-url");
console.log($select1.value);
$.ajax({                       // initialize an AJAX request
        url: url,                    // set the url request
        data: {
          'name_type_id': $select1.value       // add the name id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_electronics` view function
          $("#electronics").html(data);  // replace the contents of the electronics input with the data that came from the server
        },
        failure: function(errMsg) {
            alert(errMsg);  //message displayed when error occured
        }
      });
}
// Defining a function to call when
function collectdata(t) {
//instance of category select html element
url = 'http://127.0.0.1:8000/ajax/load_list' ;
$.ajax({
        type: "GET", //type of method used
        url: url,     // set the url request
        data: {
            'Seller_id': $(t).attr('id')   // add the seller id to the GET parameters
        },
        success: function(result) {  // 'data' is the return of the'load_list' view function
            $("#body").html(result);   // replace the contents of the seller details input with the data that came from the server
        },
        error: function(result) {
            alert('error');   //message displayed when error occured
        }
    });
};
</script>
{% endblock %}
</html>


{% endblock %}

templates/base.html
<!--Base template for the project-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" name="q" href="{% url 'max:register' %}">REGISTER</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
<!--            <li><a href="{% url 'database' %}">DATABASE</a></li>-->

          {% endif %}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a class="navbar-link" name="p" href="{% url 'max:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</html>

templates/confirmation.html
<!--Simple htlm page to print the user, product and seller details-->

<!doctype html>
<html>
<body id="hey">
 <h2><b>USER DETAILS</b></h2>

<h2>USER NAME : {{user.username}}</h2>
 <h2>USER EMAIL ID : {{user.email}}</h2>
 <h2>USER ADDRESS : {{w}}</h2>
<h2>USER MOBILE NUMBER : {{c}}</h2>

<h2><b>PRODUCT DETAILS</b></h2>
 {% for z in list %}
<h2>PRODUCT DETAILS : {{z.model_seller}}</h2>
 <br></br>

<h2><b>SELLER DETAILS</b></h2>

<h2>SELLER NAME : {{z.name}}</h2>
<h2>SELLER ADDRESS : {{z.address}}</h2>
<h2>SELLER EMAIL ID : {{z.email_id}}</h2>
<h2>SELLER PRICE : {{z.price}}</h2>
 <br></br>

<h2><b>TOTAL PRICE:{{z.price}}</b></h2>
  <br></br>
 <button id="{{z.name}}" name="r" class="btn btn-primary btn-lg active" aria-pressed="true" onclick="collectmail(this);">CONFIRM</button>
 {%endfor%}
<a href="{% url 'database' %}" class="btn btn-primary btn-lg active" name ="y" role="button" aria-pressed="true">BACK</a>
</body>
</html>


{% block javascript %}

<script>
// Defining a function to call when
function collectmail(t) {
//instance of category select html element
url = 'http://127.0.0.1:8000/ajax/subscribe' ;
$.ajax({
        type: "GET",  //type of method used
        url: url,    // set the url request
        data: {
            'Seller_id': $(t).attr('id')  // add the seller id to the GET parameters
        },
        success: function(result) {  // 'data' is the return of the'subscribe' view function
         $("#body").html(result);    // replace the contents of the user details input with the data that came from the server

        },
        error: function(result) {
            alert('error');  //message displayed when error occured
        }
    });
};
 </script>
{% endblock %}

templates/electronics_dropdown.html
<!--html page for drop down box-->
<div class="col-xs-6">
    <select class="form-control" name="select2" id="electronics">
        {% for r in nex %}
        <option value={{r.id}}>{{r.specification }}</option>

        {%endfor%}
    </select>
</div>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
{% load render_table from django_tables2 %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login </h2>
    {% endif %}
  </div>
</div>

<!--index Html page-->
 {% if user.is_authenticated %}
<a href="{% url 'database' %}" class="btn btn-primary btn-lg active" name ="y" role="button" aria-pressed="true">SELECT HERE TO CHOOSE THE ITEM YOU WANT TO PURCHASE</a>
 {% endif %}
{% endblock %}

templates/login.html
<!--Html page to create login page-->

{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'max:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="u" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/registration.html
<!--Html page to create registration page-->

{% extends "base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
        <
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" class="btn btn-primary btn-lg active" aria-pressed="true" name="g" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

templates/signup.html
<!--Html page to create signup page-->
{% extends 'base.html' %}
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
    <a href="{% url 'login' %}">Sign up</a>
  </form>



{% endblock %}

templates/success.html
<!--Html page to print success message after the emails been send -->
<!DOCTYPE html>
<html>
<head>
    <title>Success</title>
</head>
<body>
    <h1>THANKS FOR SHOPPING</h1>
<h1>MAIL HAS BEEN SENT TO THE SELLER</h1>
<h1>YOU WILL RECEIVE YOUR PRODUCT WITHIN FEW DAYS</h1>
<a href="{% url 'database' %}" class="btn btn-primary btn-lg active" name ="y" role="button" aria-pressed="true">BACK</a>

</body>
</html>

templates/table.html
<!--Table to display the details of seller related to the selected electronic device-->

<table style="width:100%" name="select3" id="sellercategory" >
    <tr>
        <th>SR NO</th>
        <th>SPECIFICATIONS</th>
        <th>NAME</th>
        <th>ADDRESS</th>
        <th>EMAIL ID</th>
        <th>PRICE</th>
        <th>SELECT</th>
    </tr>

    {% for z in sell %}
    <tr>
        <td>{{ z.srno }}</td>
        <td>{{z.model_seller}}</td>
        <td>{{z.name}}</td>
        <td>{{z.address }}</td>
        <td>{{z.email_id }}</td>
        <td>{{z.price }}</td>
        <th><button id="{{z.srno}}" name="t" onclick="collectdata(this);">BUY</button></th>
    </tr>
    {%endfor%}
</table>